joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: &robot_joints
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    elbow_joint: {trajectory: 0.1, goal: 0.1}
    wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints

velocity_controller:
  type: position_controllers/JointTrajectoryController
  # type: velocity_controllers/JointGroupVelocityController
  # type: velocity_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  gains: # Required because we're controlling a velocity interface
     shoulder_pan_joint: {p: 100,  d: 0.01, i: 10}
     shoulder_lift_joint: {p: 100,  d: 0.01, i: 10}
     elbow_joint: {p: 100,  d: 0.01, i: 10}
     wrist_1_joint: {p: 100,  d: 0.01, i: 10}
     wrist_2_joint: {p: 100,  d: 0.01, i: 10}
     wrist_3_joint: {p: 100,  d: 0.01, i: 10}
  constraints:
     goal_time: 0.6
     stopped_velocity_tolerance: 0.05
     shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
     shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
     elbow_joint: {trajectory: 0.1, goal: 0.1}
     wrist_1_joint: {trajectory: 0.1, goal: 0.1}
     wrist_2_joint: {trajectory: 0.1, goal: 0.1}
     wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_velocity_controller:
  type: position_controllers/JointGroupPositionController
  # type: velocity_controllers/JointGroupVelocityController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
