arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
     - ur5_arm_shoulder_pan_joint
     - ur5_arm_shoulder_lift_joint
     - ur5_arm_elbow_joint
     - ur5_arm_wrist_1_joint
     - ur5_arm_wrist_2_joint
     - ur5_arm_wrist_3_joint
  gains: # Required because we're controlling a velocity interface
     ur5_arm_shoulder_pan_joint: {p: 100,  d: 0.01, i: 10}
     ur5_arm_shoulder_lift_joint: {p: 100,  d: 0.01, i: 10}
     ur5_arm_elbow_joint: {p: 100,  d: 0.01, i: 10}
     ur5_arm_wrist_1_joint: {p: 100,  d: 0.01, i: 10}
     ur5_arm_wrist_2_joint: {p: 100,  d: 0.01, i: 10}
     ur5_arm_wrist_3_joint: {p: 100,  d: 0.01, i: 10}
  constraints:
     goal_time: 0.6
     stopped_velocity_tolerance: 0.05
     ur5_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
     ur5_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
     ur5_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
     ur5_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
     ur5_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
     ur5_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: effort_controllers/GripperActionController #position_controllers/GripperActionController 
  joint: finger_joint
  gains:
      finger_joint: {p: 10, d: 0.1, i: 1, i_clamp: 1}
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - ur5_arm_shoulder_pan_joint
     - ur5_arm_shoulder_lift_joint
     - ur5_arm_elbow_joint
     - ur5_arm_wrist_1_joint
     - ur5_arm_wrist_2_joint
     - ur5_arm_wrist_3_joint
